# Fly.io launch configuration
# -------------------------------------------------
# Rename the `app` value after `flyctl launch` generates
# a globally-unique application name.
# -------------------------------------------------
app = "foodvision-api"  # <-- flyctl will rewrite if this name is taken

# Build section – Fly will build directly from the existing Dockerfile
[build]
  dockerfile = "Dockerfile"

# Environment variables that get baked into the VM. Sensitive values
# (API keys, etc.) should be added later with `flyctl secrets set`.
[env]
  PORT = "8000"
  # Example (uncomment & change):
  # GEMINI_API_KEY = "${GEMINI_API_KEY}"
  # USDA_API_KEY   = "${USDA_API_KEY}"
  # REDIS_URL      = "${REDIS_URL}"

# The API exposes HTTP on port 8000 inside the VM. We map that to
# ports 80/443 externally.
[[services]]
  internal_port = 8000
  protocol      = "tcp"

  [[services.ports]]
    port     = 80
    handlers = ["http"]

  [[services.ports]]
    port     = 443
    handlers = ["tls", "http"]

  # Optional concurrency limits
  [services.concurrency]
    type        = "requests"
    soft_limit  = 50
    hard_limit  = 100

  # Basic liveness check – HTTP GET /
  [[services.http_checks]]
    interval       = "15s"
    timeout        = "2s"
    grace_period   = "10s"
    method         = "get"
    path           = "/"
    protocol       = "http"
    tls_skip_verify = false
    restart_limit  = 0 